### ISSUE TITLE
Email not working (again)

### ISSUE THREAD

**Issue by gladwynlewis83** [badili/erpnext#26]
Emails work when using PDF attachment with Unquoted Excel file (or any other attachments), but do not work, when we use the Excel quotation

Reason being is that the Excel files are getting Added and Removed automatically. Please see the attached screenshot

![image](https://cloud.githubusercontent.com/assets/22613192/19220301/833a7b10-8e3b-11e6-8344-9fe11de758df.png)

**Comment by gladwynlewis83** [comment]
When you go to the print section of any document and click on Excel, it outputs this error.

**Comment by gladwynlewis83** [comment]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 49, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/print_format.py", line 64, in download_excel
    fname = get_excel(doctype, name, format)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/excel.py", line 48, in get_excel
    output_sheet_header(doc, meta, cur_worksheet, starting_row, starting_col, workbook)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/excel.py", line 59, in output_sheet_header
    letterhead_path = "%s%s" % ('site1.local/public', matchObj.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by gladwynlewis83** [comment]
`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 49, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/print_format.py", line 64, in download_excel
    fname = get_excel(doctype, name, format)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/excel.py", line 48, in get_excel
    output_sheet_header(doc, meta, cur_worksheet, starting_row, starting_col, workbook)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/excel.py", line 59, in output_sheet_header
    letterhead_path = "%s%s" % ('site1.local/public', matchObj.group(1))
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by soloincc** [comment]
Done. Test, confirm and close the issue

**Comment by gladwynlewis83** [comment]
I've checked it, it's generating the excel sheet now, but emails are yet not going out.

**Comment by gladwynlewis83** [comment]
![image](https://cloud.githubusercontent.com/assets/22613192/19229890/fc760336-8ee1-11e6-86a2-b20e4f058afb.png)
As you can see it is yet removing the xls files from the system. Could this be the issue?

**Comment by gladwynlewis83** [comment]
This is the format for the PDF. Which is perfectly fine. 

![image](https://cloud.githubusercontent.com/assets/22613192/19229958/7a942c2a-8ee2-11e6-9978-6a321e2dc829.png)

And this is the format for the Excel sheet, as you can see the format of the fields don't match at all.

![image](https://cloud.githubusercontent.com/assets/22613192/19229984/a8435d3a-8ee2-11e6-93c0-1702a07d4905.png)

Pricing Rule should be hidden, and the Serial No should be the first field. We don't want the customers to know what our pricing rules are
